
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Feb 11 11:23:19 IST 2020
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SPACE = 25;
  public static final int MULT = 3;
  public static final int CHAR = 33;
  public static final int LESSE = 21;
  public static final int GREAT = 20;
  public static final int LPAREN = 9;
  public static final int SEMI = 12;
  public static final int INT = 31;
  public static final int LESS = 19;
  public static final int FOR = 27;
  public static final int MINUS = 5;
  public static final int CS = 16;
  public static final int RPAREN = 10;
  public static final int OS = 15;
  public static final int COMMA = 30;
  public static final int DIV = 6;
  public static final int PLUS = 4;
  public static final int IF = 17;
  public static final int DOT = 14;
  public static final int ID = 7;
  public static final int EOF = 0;
  public static final int EQUAL = 8;
  public static final int error = 1;
  public static final int MOD = 11;
  public static final int NEQ = 24;
  public static final int VOID = 35;
  public static final int EQ = 23;
  public static final int LCB = 28;
  public static final int ELSE = 18;
  public static final int EOFILE = 13;
  public static final int WHILE = 26;
  public static final int FLOAT = 32;
  public static final int NEWL = 36;
  public static final int GREATE = 22;
  public static final int INTVAL = 2;
  public static final int STRING = 34;
  public static final int RCB = 29;
}

