
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Jan 21 09:58:00 IST 2020
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INT = 2;
  public static final int EOFILE = 8;
  public static final int SEMI = 4;
  public static final int EOF = 0;
  public static final int STRING = 3;
  public static final int ID = 6;
  public static final int error = 1;
  public static final int COMMA = 5;
  public static final int SPACE = 7;
  public static final int CHAR = 10;
  public static final int FLOAT = 9;
}

