
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Jan 28 11:33:13 IST 2020
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CS = 15;
  public static final int OS = 14;
  public static final int INT = 2;
  public static final int STRVAL = 13;
  public static final int EQUAL = 10;
  public static final int SEMI = 4;
  public static final int FLOATVAL = 18;
  public static final int CC = 17;
  public static final int ID = 6;
  public static final int SPACE = 7;
  public static final int OC = 16;
  public static final int INTVAL = 11;
  public static final int STRING = 3;
  public static final int COMMA = 5;
  public static final int FLOAT = 19;
  public static final int NULLVAL = 21;
  public static final int EOF = 0;
  public static final int CONST = 20;
  public static final int error = 1;
  public static final int EOFILE = 8;
  public static final int NEWL = 9;
  public static final int VAR = 12;
}

