
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Feb 02 09:19:59 IST 2020
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CS = 17;
  public static final int MOD = 12;
  public static final int OS = 16;
  public static final int PLUS = 4;
  public static final int RPAREN = 11;
  public static final int EQUAL = 8;
  public static final int SEMI = 13;
  public static final int LPAREN = 10;
  public static final int ID = 7;
  public static final int INTVAL = 2;
  public static final int EOF = 0;
  public static final int MULT = 3;
  public static final int DIV = 6;
  public static final int MINUS = 5;
  public static final int error = 1;
  public static final int DOT = 15;
  public static final int EOFILE = 14;
  public static final int NEWL = 9;
}

